import { and } from "tiny-guards";
and satisfies object;
import { and as and$2 } from "tiny-guards/and";
and$2 satisfies object;
import { array } from "tiny-guards";
array satisfies object;
import { array as array$2 } from "tiny-guards/array";
array$2 satisfies object;
import { endsWith } from "tiny-guards";
endsWith satisfies object;
import { endsWith as endsWith$2 } from "tiny-guards/endsWith";
endsWith$2 satisfies object;
import { gt } from "tiny-guards";
gt satisfies object;
import { gt as gt$2 } from "tiny-guards/gt";
gt$2 satisfies object;
import { gte } from "tiny-guards";
gte satisfies object;
import { gte as gte$2 } from "tiny-guards/gte";
gte$2 satisfies object;
import { instance } from "tiny-guards";
instance satisfies object;
import { instance as instance$2 } from "tiny-guards/instance";
instance$2 satisfies object;
import { isBigInt } from "tiny-guards";
isBigInt satisfies object;
import { isBigInt as isBigInt$2 } from "tiny-guards/isBigInt";
isBigInt$2 satisfies object;
import { isBoolean } from "tiny-guards";
isBoolean satisfies object;
import { isBoolean as isBoolean$2 } from "tiny-guards/isBoolean";
isBoolean$2 satisfies object;
import { isCapitalized } from "tiny-guards";
isCapitalized satisfies object;
import { isCapitalized as isCapitalized$2 } from "tiny-guards/isCapitalized";
isCapitalized$2 satisfies object;
import { isFunction } from "tiny-guards";
isFunction satisfies object;
import { isFunction as isFunction$2 } from "tiny-guards/isFunction";
isFunction$2 satisfies object;
import { isLowercase } from "tiny-guards";
isLowercase satisfies object;
import { isLowercase as isLowercase$2 } from "tiny-guards/isLowercase";
isLowercase$2 satisfies object;
import { isNull } from "tiny-guards";
isNull satisfies object;
import { isNull as isNull$2 } from "tiny-guards/isNull";
isNull$2 satisfies object;
import { isNumber } from "tiny-guards";
isNumber satisfies object;
import { isNumber as isNumber$2 } from "tiny-guards/isNumber";
isNumber$2 satisfies object;
import { isObject } from "tiny-guards";
isObject satisfies object;
import { isObject as isObject$2 } from "tiny-guards/isObject";
isObject$2 satisfies object;
import { isPrimitive } from "tiny-guards";
isPrimitive satisfies object;
import { isPrimitive as isPrimitive$2 } from "tiny-guards/isPrimitive";
isPrimitive$2 satisfies object;
import { isString } from "tiny-guards";
isString satisfies object;
import { isString as isString$2 } from "tiny-guards/isString";
isString$2 satisfies object;
import { isSymbol } from "tiny-guards";
isSymbol satisfies object;
import { isSymbol as isSymbol$2 } from "tiny-guards/isSymbol";
isSymbol$2 satisfies object;
import { isUncapitalized } from "tiny-guards";
isUncapitalized satisfies object;
import { isUncapitalized as isUncapitalized$2 } from "tiny-guards/isUncapitalized";
isUncapitalized$2 satisfies object;
import { isUndefined } from "tiny-guards";
isUndefined satisfies object;
import { isUndefined as isUndefined$2 } from "tiny-guards/isUndefined";
isUndefined$2 satisfies object;
import { isUppercase } from "tiny-guards";
isUppercase satisfies object;
import { isUppercase as isUppercase$2 } from "tiny-guards/isUppercase";
isUppercase$2 satisfies object;
import { len } from "tiny-guards";
len satisfies object;
import { len as len$2 } from "tiny-guards/len";
len$2 satisfies object;
import { literal } from "tiny-guards";
literal satisfies object;
import { literal as literal$2 } from "tiny-guards/literal";
literal$2 satisfies object;
import { lt } from "tiny-guards";
lt satisfies object;
import { lt as lt$2 } from "tiny-guards/lt";
lt$2 satisfies object;
import { lte } from "tiny-guards";
lte satisfies object;
import { lte as lte$2 } from "tiny-guards/lte";
lte$2 satisfies object;
import { maxLen } from "tiny-guards";
maxLen satisfies object;
import { maxLen as maxLen$2 } from "tiny-guards/maxLen";
maxLen$2 satisfies object;
import { minLen } from "tiny-guards";
minLen satisfies object;
import { minLen as minLen$2 } from "tiny-guards/minLen";
minLen$2 satisfies object;
import { narrow } from "tiny-guards";
narrow satisfies object;
import { narrow as narrow$2 } from "tiny-guards/narrow";
narrow$2 satisfies object;
import { nullable } from "tiny-guards";
nullable satisfies object;
import { nullable as nullable$2 } from "tiny-guards/nullable";
nullable$2 satisfies object;
import { nullish } from "tiny-guards";
nullish satisfies object;
import { nullish as nullish$2 } from "tiny-guards/nullish";
nullish$2 satisfies object;
import { oneOf } from "tiny-guards";
oneOf satisfies object;
import { oneOf as oneOf$2 } from "tiny-guards/oneOf";
oneOf$2 satisfies object;
import { optional } from "tiny-guards";
optional satisfies object;
import { optional as optional$2 } from "tiny-guards/optional";
optional$2 satisfies object;
import { or } from "tiny-guards";
or satisfies object;
import { or as or$2 } from "tiny-guards/or";
or$2 satisfies object;
import { record } from "tiny-guards";
record satisfies object;
import { record as record$2 } from "tiny-guards/record";
record$2 satisfies object;
import { refine } from "tiny-guards";
refine satisfies object;
import { refine as refine$2 } from "tiny-guards/refine";
refine$2 satisfies object;
import { shape } from "tiny-guards";
shape satisfies object;
import { shape as shape$2 } from "tiny-guards/shape";
shape$2 satisfies object;
import { startsWith } from "tiny-guards";
startsWith satisfies object;
import { startsWith as startsWith$2 } from "tiny-guards/startsWith";
startsWith$2 satisfies object;
import { tinyGuards } from "tiny-guards";
tinyGuards satisfies object;
import { tinyGuards as tinyGuards$2 } from "tiny-guards/tinyGuards";
tinyGuards$2 satisfies object;
import { tuple } from "tiny-guards";
tuple satisfies object;
import { tuple as tuple$2 } from "tiny-guards/tuple";
tuple$2 satisfies object;
